workers_dev = true
name = "croissant"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
# assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "DB"
database_name = "croissant"
database_id = "6dfa01b6-879b-4b9c-a621-67660a32d534"
migrations_dir = "drizzle"

[vars]
DATABASE_ID = "6dfa01b6-879b-4b9c-a621-67660a32d534"
